### ISSUE TITLE
PostgreSQL Version

### ISSUE THREAD

**Issue by tfuerholzer** [rstropek-teaching/address-book-quiz-4ahif-tfuerholzer#1]
I have created a PostgreSQL version of this exercise too. It can be found under https://github.com/tfuerholzer/adressbook-postgre/tree/master

I decided to use PostgreSQL instead of MySQL since my hoster (heroku) has it built in.

I also hosted the solution (the postgre version) here : https://restcontactapi.herokuapp.com/contacts

It might load take a bit to load because in my free plan the server goes to "sleep mode" after 30 mins and takes some time to restart.

**Comment by rstropek** [comment]
@tfuerholzer That's great 👍 Your code is already quite good. I took a close look and gathered some tips that could help you to further improve your coding skills:

* I would consider using [*pg-promise*](https://github.com/vitaly-t/pg-promise) instead of *node-postgres*. *pg-promise* adds a bunch of features (including `async/await`) that makes you more productive when writing DB-related apps.

* In Typescript, you do not need to include types in documentation (e.g. just write `@param id ...` insted of `@param {int} id ...`.

* Avoid [unused variables](https://github.com/tfuerholzer/adressbook-postgre/blob/ad203f7160c5496ad53dbd4b2d6ddab423412f27/contact-main.ts#L38).

* Use `console.error` instead of `console.log` to print error messages ([examples](https://github.com/tfuerholzer/adressbook-postgre/blob/ad203f7160c5496ad53dbd4b2d6ddab423412f27/contact-main.ts#L41)).

* Avoid combining multiple responsibilities in a single class. Your class `Person` is on the one hand a data transfer object (DTO) holding all properties of a person. On the other hand, it contains data access methods. This violates the [single responsibility pattern](https://en.wikipedia.org/wiki/Single_responsibility_principle). My tip: Put data access methods in a separate class).

* Avoid [passing a boolean value to a callback](https://github.com/tfuerholzer/adressbook-postgre/blob/ad203f7160c5496ad53dbd4b2d6ddab423412f27/contact-main.ts#L35) indicating success or failure. Instead, take two callbacks: One for success and one for failure. See [*Promise* constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) for example. As an alternative, you could pass an error object (not just boolean) to the callback.

* Try to avoid [unnecessarily complex code](https://github.com/tfuerholzer/adressbook-postgre/blob/ad203f7160c5496ad53dbd4b2d6ddab423412f27/contact-main.ts#L61). In that case, you could just call `callback(!error)`.

* Consider [*restify-errors*](https://github.com/restify/errors) in cases like [that](https://github.com/tfuerholzer/adressbook-postgre/blob/ad203f7160c5496ad53dbd4b2d6ddab423412f27/contact-get.ts#L12).

* Consider returning 204 (*No Content*) instead of 200 in case of HTTP Delete. 204 is more common in professional web APIs.

* Avoid sending data that does not add value to the HTTP status code ([example](https://github.com/tfuerholzer/adressbook-postgre/blob/ad203f7160c5496ad53dbd4b2d6ddab423412f27/contact-delete.ts#L11)). This just makes your app slower because the text has to be transmitted.

* Write `!request.body.id` instead of `request.body.id === undefined`. This would cover `null`, too, which makes your code even more robust against wrong input data.

* Avoid data type in cases like `let description: string = "";`. `let description = "";` would be enough.

I would like to congratulate you again to your app. Well done! I hope you find my comments above useful.

Greetings,
Rainer Stropek.
